# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: led-api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rled-api.proto\x12\x0bled_service\"o\n\x0fLightLEDRequest\x12\x34\n\x04mode\x18\x01 \x01(\x0e\x32&.led_service.LightLEDRequest.LightMode\"&\n\tLightMode\x12\x0b\n\x07NO_MODE\x10\x00\x12\x0c\n\x08KEY_WORD\x10\x01\"#\n\x10LightLEDResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32W\n\nLedService\x12I\n\x08LightLED\x12\x1c.led_service.LightLEDRequest\x1a\x1d.led_service.LightLEDResponse\"\x00\x42\x11Z\x0f\x61pi/led-serviceb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'led_api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\017api/led-service'
  _LIGHTLEDREQUEST._serialized_start=30
  _LIGHTLEDREQUEST._serialized_end=141
  _LIGHTLEDREQUEST_LIGHTMODE._serialized_start=103
  _LIGHTLEDREQUEST_LIGHTMODE._serialized_end=141
  _LIGHTLEDRESPONSE._serialized_start=143
  _LIGHTLEDRESPONSE._serialized_end=178
  _LEDSERVICE._serialized_start=180
  _LEDSERVICE._serialized_end=267
# @@protoc_insertion_point(module_scope)
